[workspace]
resolver = "2"
members = ["crates/nethop-subscription"]
exclude = ["crates/nethop-subscription/fuzz"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.86"
license = "AGPL-3.0-only"
repository = "https://github.com/jinghu-moon/NetHop"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
incremental = false
